### ISSUE TITLE
Can not build on MacOS 10.11.3 

### ISSUE THREAD

**Issue by xworks** [omochi/libwebsockets-ios-build#1]
The error:

➜  libwebsockets-ios-build git:(master) ./websockets-ios-build.rb 
./websockets-ios-build.rb:60:in `make_output_dir': undefined method`binwrite' for #Pathname:0x007fb47c0050e0 (NoMethodError)
    from ./websockets-ios-build.rb:106:in `build'
    from ./websockets-ios-build.rb:50:in`main'
    from ./websockets-ios-build.rb:233:in `<main>'

**Comment by omochi** [comment]
Which version of ruby do you use?
`IO.binwrite` method is from ruby 1.9.3.

This script has been tested with ruby 2.2.3.
https://github.com/omochi/libwebsockets-ios-build/blob/master/.travis.yml

**Comment by xworks** [comment]
➜  libwebsockets-ios-build git:(master) ✗ ruby -version
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

I have fixed it by doing this:

```
diff --git a/websockets-ios-build.rb b/websockets-ios-build.rb
index be5ae1e..a98b807 100755
--- a/websockets-ios-build.rb
+++ b/websockets-ios-build.rb
@@ -57,7 +57,8 @@ class App
        def make_output_dir
                dir = output_dir
                dir.mkpath
-               (dir + ".keep").binwrite("")
+               #(dir + ".keep").binwrite("")
+        IO.binwrite(dir + ".keep", "")
        end
        def set_target(platform, arch)
                @platform = platform
@@ -162,7 +163,8 @@ class App
                Dir.chdir(script_dir.to_s)

                log_file = dir + "build.log"
-               log_file.binwrite("")
+               #log_file.binwrite("")
+        IO.binwrite(log_file, "")

                cmd = ["xcodebuild", "-project", "websockets.xcodeproj",
                        "-target", "websockets",
@@ -230,4 +232,4 @@ class App
 end

```

**Comment by omochi** [comment]
@xworks 
Sorry I was wrong.
In this case, we need the method `Pathname#binwrite`. not `IO.binwrite`

It is from ruby 2.1.0.

2.0.0
http://docs.ruby-lang.org/ja/2.0.0/class/Pathname.html

2.1.0
http://docs.ruby-lang.org/ja/2.1.0/class/Pathname.html

Please use ruby 2.1.0 or later.
