### ISSUE TITLE
Build failure on MAC OS 10.11.4

### ISSUE THREAD

**Issue by Kushi171987** [omochi/libwebsockets-ios-build#2]
`./websockets-ios-build.rb:212:in`exec': exec failed: status=pid 7434 exit 2, command=./build-libssl.sh --no-spinner (RuntimeError)
    from ./websockets-ios-build.rb:103:in `build'
    from ./websockets-ios-build.rb:50:in`main'
    from ./websockets-ios-build.rb:235:in `<main>'`

**Comment by omochi** [comment]
This issue is in building openssl with my fork
https://github.com/omochi/OpenSSL-for-iPhone

It outputs detail log file
please see there.
